// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {context} from '../models';

export function CreateChapter(arg1:number,arg2:string,arg3:string,arg4:string):Promise<application.Chapter>;

export function CreateMatiere(arg1:string,arg2:string):Promise<application.MatiereSummary>;

export function CreateSubjectWork(arg1:number,arg2:string,arg3:string):Promise<application.SubjectWork>;

export function DeleteAttachment(arg1:number):Promise<void>;

export function DeleteChapter(arg1:number):Promise<void>;

export function DeleteMatiere(arg1:number):Promise<void>;

export function DeleteSubjectWork(arg1:number):Promise<void>;

export function GetDashboard():Promise<application.Dashboard>;

export function GetMatiereDetail(arg1:number):Promise<application.MatiereDetail>;

export function ImportChapterFiles(arg1:number,arg2:Array<string>):Promise<application.ImportResult>;

export function ListMatieres():Promise<Array<application.MatiereSummary>>;

export function ListPastelColors():Promise<Array<string>>;

export function MoveAttachment(arg1:number,arg2:number):Promise<void>;

export function OpenAttachment(arg1:number):Promise<void>;

export function RenameAttachment(arg1:number,arg2:string):Promise<void>;

export function RenameMatiere(arg1:number,arg2:string):Promise<void>;

export function SelectAndImportChapterFiles(arg1:number):Promise<application.ImportResult>;

export function SetChapterStatus(arg1:number,arg2:string):Promise<void>;

export function SetSubjectWorkCompleted(arg1:number,arg2:boolean):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleTodayTask(arg1:number,arg2:boolean):Promise<void>;

export function UpdateChapter(arg1:number,arg2:string,arg3:string):Promise<void>;
