// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {context} from '../models';

export function CreateChapter(arg1:number,arg2:string,arg3:string,arg4:string):Promise<application.Chapter>;

export function CreateMatiere(arg1:string,arg2:string):Promise<application.MatiereSummary>;

export function CreatePlanningTask(arg1:application.PlanningTaskInput):Promise<application.PlanningTask>;

export function CreateQuizQuestion(arg1:application.QuizQuestionInput):Promise<application.QuizQuestion>;

export function CreateSubjectWork(arg1:number,arg2:string,arg3:string):Promise<application.SubjectWork>;

export function DeleteAttachment(arg1:number):Promise<void>;

export function DeleteChapter(arg1:number):Promise<void>;

export function DeleteMatiere(arg1:number):Promise<void>;

export function DeletePlanningTask(arg1:number):Promise<void>;

export function DeleteQuizQuestion(arg1:number):Promise<void>;

export function DeleteSubjectWork(arg1:number):Promise<void>;

export function DownloadPlanningTemplate():Promise<void>;

export function GeneratePlanning(arg1:application.GeneratePlanningInput):Promise<Array<application.PlanningTask>>;

export function GetDailyQuiz():Promise<application.DailyQuiz>;

export function GetDashboard():Promise<application.Dashboard>;

export function GetMatiereDetail(arg1:number):Promise<application.MatiereDetail>;

export function GetQuizProgress():Promise<application.QuizProgress>;

export function GetWorkdayPreferences():Promise<application.WorkdayPreferences>;

export function ImportChapterFiles(arg1:number,arg2:Array<string>):Promise<application.ImportResult>;

export function ImportPlanningTemplate():Promise<application.ImportResult>;

export function ListMatieres():Promise<Array<application.MatiereSummary>>;

export function ListPastelColors():Promise<Array<string>>;

export function ListPlanningData():Promise<application.PlanningData>;

export function ListPlanningTasks(arg1:string,arg2:string):Promise<Array<application.PlanningTask>>;

export function ListQuizQuestions():Promise<Array<application.QuizQuestion>>;

export function MoveAttachment(arg1:number,arg2:number):Promise<void>;

export function MovePlanningTask(arg1:number,arg2:string,arg3:string,arg4:string):Promise<application.PlanningTask>;

export function OpenAttachment(arg1:number):Promise<void>;

export function RenameAttachment(arg1:number,arg2:string):Promise<void>;

export function RenameMatiere(arg1:number,arg2:string):Promise<void>;

export function SaveWorkdayPreferences(arg1:application.WorkdayPreferences):Promise<void>;

export function SelectAndImportChapterFiles(arg1:number):Promise<application.ImportResult>;

export function SetChapterStatus(arg1:number,arg2:string):Promise<void>;

export function SetSubjectWorkCompleted(arg1:number,arg2:boolean):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SubmitDailyQuiz(arg1:Array<number>,arg2:boolean):Promise<application.QuizResult>;

export function ToggleTodayTask(arg1:number,arg2:boolean):Promise<void>;

export function UpdateChapter(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdatePlanningTask(arg1:number,arg2:application.PlanningTaskInput):Promise<application.PlanningTask>;

export function UpdateQuizQuestion(arg1:number,arg2:application.QuizQuestionInput):Promise<void>;
