// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDashboard():Promise<main.Dashboard>;

export function ToggleTodayTask(arg1:number,arg2:boolean):Promise<void>;
