// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChapter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateChapter'](arg1, arg2, arg3, arg4);
}

export function CreateMatiere(arg1, arg2) {
  return window['go']['main']['App']['CreateMatiere'](arg1, arg2);
}

export function CreatePlanningTask(arg1) {
  return window['go']['main']['App']['CreatePlanningTask'](arg1);
}

export function CreateQuizQuestion(arg1) {
  return window['go']['main']['App']['CreateQuizQuestion'](arg1);
}

export function CreateSubjectWork(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSubjectWork'](arg1, arg2, arg3);
}

export function DeleteAttachment(arg1) {
  return window['go']['main']['App']['DeleteAttachment'](arg1);
}

export function DeleteChapter(arg1) {
  return window['go']['main']['App']['DeleteChapter'](arg1);
}

export function DeleteMatiere(arg1) {
  return window['go']['main']['App']['DeleteMatiere'](arg1);
}

export function DeletePlanningTask(arg1) {
  return window['go']['main']['App']['DeletePlanningTask'](arg1);
}

export function DeleteQuizQuestion(arg1) {
  return window['go']['main']['App']['DeleteQuizQuestion'](arg1);
}

export function DeleteSubjectWork(arg1) {
  return window['go']['main']['App']['DeleteSubjectWork'](arg1);
}

export function DownloadPlanningTemplate() {
  return window['go']['main']['App']['DownloadPlanningTemplate']();
}

export function GeneratePlanning(arg1) {
  return window['go']['main']['App']['GeneratePlanning'](arg1);
}

export function GetDailyQuiz() {
  return window['go']['main']['App']['GetDailyQuiz']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetMatiereDetail(arg1) {
  return window['go']['main']['App']['GetMatiereDetail'](arg1);
}

export function GetQuizProgress() {
  return window['go']['main']['App']['GetQuizProgress']();
}

export function GetWorkdayPreferences() {
  return window['go']['main']['App']['GetWorkdayPreferences']();
}

export function ImportChapterFiles(arg1, arg2) {
  return window['go']['main']['App']['ImportChapterFiles'](arg1, arg2);
}

export function ImportPlanningTemplate() {
  return window['go']['main']['App']['ImportPlanningTemplate']();
}

export function ListMatieres() {
  return window['go']['main']['App']['ListMatieres']();
}

export function ListPastelColors() {
  return window['go']['main']['App']['ListPastelColors']();
}

export function ListPlanningData() {
  return window['go']['main']['App']['ListPlanningData']();
}

export function ListPlanningTasks(arg1, arg2) {
  return window['go']['main']['App']['ListPlanningTasks'](arg1, arg2);
}

export function ListQuizQuestions() {
  return window['go']['main']['App']['ListQuizQuestions']();
}

export function MoveAttachment(arg1, arg2) {
  return window['go']['main']['App']['MoveAttachment'](arg1, arg2);
}

export function MovePlanningTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MovePlanningTask'](arg1, arg2, arg3, arg4);
}

export function OpenAttachment(arg1) {
  return window['go']['main']['App']['OpenAttachment'](arg1);
}

export function RenameAttachment(arg1, arg2) {
  return window['go']['main']['App']['RenameAttachment'](arg1, arg2);
}

export function RenameMatiere(arg1, arg2) {
  return window['go']['main']['App']['RenameMatiere'](arg1, arg2);
}

export function SaveWorkdayPreferences(arg1) {
  return window['go']['main']['App']['SaveWorkdayPreferences'](arg1);
}

export function SelectAndImportChapterFiles(arg1) {
  return window['go']['main']['App']['SelectAndImportChapterFiles'](arg1);
}

export function SetChapterStatus(arg1, arg2) {
  return window['go']['main']['App']['SetChapterStatus'](arg1, arg2);
}

export function SetSubjectWorkCompleted(arg1, arg2) {
  return window['go']['main']['App']['SetSubjectWorkCompleted'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function SubmitDailyQuiz(arg1, arg2) {
  return window['go']['main']['App']['SubmitDailyQuiz'](arg1, arg2);
}

export function ToggleTodayTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleTodayTask'](arg1, arg2);
}

export function UpdateChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateChapter'](arg1, arg2, arg3);
}

export function UpdatePlanningTask(arg1, arg2) {
  return window['go']['main']['App']['UpdatePlanningTask'](arg1, arg2);
}

export function UpdateQuizQuestion(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuizQuestion'](arg1, arg2);
}
