// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function ToggleTodayTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleTodayTask'](arg1, arg2);
}
